apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mycve-app
images:
- digest:
  name: mycve-app
  newName: harbor.lab.pksdemo.net/tanzu/mycve/mycve-app
resources:
- mycve-app-deploy.yaml
- mycve-app-svc.yaml
