apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mycve-app
images:
- digest: sha256:f14c4b25506b4712306be58d4a872a095a01559c6072ddc163f3a26d81e5fd15
  name: mycve-app
  newName: harbor.lab.pksdemo.net/tanzu/app/mycve-app
resources:
- mycve-app-deploy.yaml
- mycve-app-svc.yaml
