apiVersion: v1
kind: Service
metadata:
  labels:
    app: mycve-app
  name: mycve-app-svc
  namespace: mycve-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mycve-app
  type: NodePort
