apiVersion: v1
kind: Service
metadata:
  labels:
    app: mycve-test
  name: mycve-test-svc
  namespace: mycve-test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mycve-test
  type: NodePort
